CREATE TABLE EXT_OWNERSHIP(
ID uuid,
CREATE_TS TIMESTAMP,
CREATED_BY VARCHAR(50),
VERSION INTEGER,
UPDATE_TS TIMESTAMP,
UPDATED_BY VARCHAR(50),
DELETE_TS TIMESTAMP,
DELETED_BY VARCHAR(50),
NAME VARCHAR(100),
CODE VARCHAR(50) NOT NULL,
PRIMARY KEY(ID)
);

